services:
  - type: web
    name: my-streamlit-app
    env: python
    buildCommand: |
      apt-get update && apt-get install -y openjdk-11-jre-headless
      pip install -r requirements.txt
    startCommand: streamlit run app.py
